name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          yarn install
          yarn build

      - name: Build Backend
        run: |
          cd backend
          cargo build --release

      - name: Run Tests
        run: |
          cd backend
          cargo test
